In [1]:
s = "This is online AI course"
print(type(s))

<class 'str'>


In [2]:
print(s[len(s)-1])

e


In [3]:
s[5:10]

'is on'

In [4]:
a = [10,20.5,"hello"] #list
print(a[2])

hello


In [5]:
#tuple
t=(1,1.5,"ML")
print(t)

(1, 1.5, 'ML')


In [6]:
#set
a= {10,20,30,40}
print(a)

{40, 10, 20, 30}


In [9]:
print(a[1]) #can't print particular element in set,it's unorder collections of items

TypeError: 'set' object is not subscriptable

In [10]:
#dictionary
d= {'a':"apple",'b':"bat"}
print(d['a'])

apple


In [12]:
user = "satish"
lines = 100
print("Congratulations, " + user + " you just wrote " + str(lines) + "line")

Congratulations, satish you just wrote 100line


In [13]:
a = [1,2,3]
print(type(a))
s = set(a)
print(type(s))

<class 'list'>
<class 'set'>


In [14]:
list("Hello")

['H', 'e', 'l', 'l', 'o']

In [2]:
a=10;b=20
print("The value of a is {} and b is {}".format(a,b))

The value of a is 10 and b is 20


In [3]:
a= 10; b=20
print("The value of b is {1} and b is {0}".format(a,b))

The value of b is 20 and b is 10


In [4]:
#we can use keyword argument to format the string
print("Hello {name},{greeting}".format(name="satish",greeting="Good Morning"))

Hello satish,Good Morning


In [5]:
print('The story of {0},{1},and {other}'.format('Bill','Manfred',other='Georg'))

The story of Bill,Manfred,and Georg


In [7]:
a,b=10,4
#bitwise and
print(a & b)
#bitwise or
print(a | b)

0
14


In [8]:
#is and is not they checks the variables are located on the same part or not
a =5
b=5
print(a is b)

True


In [10]:
#not true for list
l1 = [1,2,3]
l2 = [1,2,3]
print(l1 is l2)
s1 = "AAIC"
s2 = "AAIC"
print(s1 is s2)

False
True


In [12]:
lst = [1,2,3,4]
print(1 in lst)
d = {1: "a",2: "b"}
print(1 in d)

True
True


In [13]:
#while loop
lst = [10,20,30,40,50]
product =1
index =0
while index < len(lst):
    product *= lst[index]
    index+=1
print("Product is : {}".format(product))

Product is : 12000000


In [14]:
num = int(input("Enter a number: "))
isDivisible = False;
i=2;
while i<num:
    if num%i == 0:
        isDivisible = True
        print("{} is divisible by {}".format(num,i))
    i+=1
if isDivisible:
    print("{} is NOT a prime number".format(num))
else:
    print("{} is a prime number".format(num))

Enter a number: 12
12 is divisible by 2
12 is divisible by 3
12 is divisible by 4
12 is divisible by 6
12 is NOT a prime number


In [19]:
#lists of list
list1 = [[1,2],[3,4]]
print(list1)
#list append
list3 = ['one','two','three','four']
list2 = ['five','six']
list3.append(list2)
print(list3)
list3.extend(list2)
print(list3)

[[1, 2], [3, 4]]
['one', 'two', 'three', 'four', ['five', 'six']]
['one', 'two', 'three', 'four', ['five', 'six'], 'five', 'six']


In [22]:
lst = ['one','two','three']
del lst[1]
print(lst)
a = lst.pop(1)
print(a)

['one', 'three']
three


In [26]:
#default split is white-charachter: space or tab
s = "This,is,applied,AI,course"
split_lst = s.split()
print(split_lst)

['This,is,applied,AI,course']


In [28]:
numbers = [10,10,20,30,40,50,60,70]
print(numbers[:])
print(numbers[0:4])
print(numbers.count(10))

[10, 10, 20, 30, 40, 50, 60, 70]
[10, 10, 20, 30]
2


In [32]:
#without list comprenshion
squares = []
for i in range(10):
    squares.append(i**2) #list append
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [34]:
#with list comprenshion
squares = [i**2 for i in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [35]:
lst = [-10,-20,10,20,50]
#create a new list with value double
new_lst = [i*2 for i in lst]
print(new_lst)

#filter the list to exclude negative numbers
new_lst = [i for i in lst if i>=0]
print(new_lst)

#create a list of tuples like (number,squares_of_numbers)
new_list = [(i,i**2) for i in range(10)]
print(new_list)

[-20, -40, 20, 40, 100]
[10, 20, 50]
[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]


In [36]:
#here is a matrix which one is lists of a list
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12] 
]
transposed = []
for i in range(4):
    lst = []
    for row in matrix: #here take row of each coloumn
        lst.append(row[i])
    transposed.append(lst)
print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [37]:
transposed= [[row[i] for row in matrix] for i in range(4)]
print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [39]:
#empty tuple
t =()
print(t)
#tuple have mixed datatypes
t = (1,'raju',28,'abc')
print(t)
#nested tuple(tuple with list and tuple)
t = (1,(2,3,4),[1,'raju',25,'abc'])
print(t)

()
(1, 'raju', 28, 'abc')
(1, (2, 3, 4), [1, 'raju', 25, 'abc'])


In [43]:
#only parenthesis is not enogh
t = ('satish')
type(t)


tuple

In [44]:
#need a comma at the end
t=('satish',)
type(t)
#parenthesis is optional
s= "azhar"
print(type(s))
print(s)

<class 'str'>
azhar


In [45]:
#nested tuple
t =('ABC',('azhar','naveen','srinu'))
print(t[1][2])

srinu


In [46]:
t = [1,2,3,4,5,6]
#print elements from starting to 2nd last element
print(t[:-2])
#print elements from starting to end
print(t[:])

[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]


In [48]:
t = (1,2,3,4,[5,6,7])
#t[2] = 'x' #will get type error
t[4][1] = "azhar" #inside in list in tuple,we can change the value
print(t)

(1, 2, 3, 4, [5, 'azhar', 7])


In [49]:
#conctenating tuples
t = (1,2,3) + (4,5,6)
print(t)

(1, 2, 3, 4, 5, 6)


In [51]:
t = (('satish',)*4)
print(t)

('satish', 'satish', 'satish', 'satish')


In [57]:
#tuple deletion
#delete a entire tuple using del keyword
t =(1,2,3,4,5,6,7)
del t

#tuple count
t = (1,2,3,4,5,1,1,3,4)
t.count(1)

#tuple index
t = (1,2,3,2,4,2)
print(t.index(2)) #return index of the first element is equal to 2

#tuple membership
x = (1,2,3,4,5)
print(1 in x)

1
True


In [58]:
#we can make set from list
s = set([1,2,3,4])
print(s)

{1, 2, 3, 4}


In [61]:
s = {1,3}
# print(s[1]) #set object doesn't support indexing
s.add(2) #add command using for add one element
print(s)
s.update([2,3,4]) #update command using for add multiple elements
print(s)

#add list and set
s.update([8,9],{10,11,12})
print(s)

{1, 2, 3}
{1, 2, 3, 4}
{1, 2, 3, 4, 8, 9, 10, 11, 12}


In [64]:
#a particular item can be delete by using discard or remove method
x = {1,2,3,4,5}
x.discard(4)
print(x)
x.remove(3)
print(x)
# x.remove(7) #will get keyerror
# x.discard(7) #will not get a keyerror
x.pop() #remove random element
print(x)

{1, 2, 3, 5}
{1, 2, 5}
{2, 5}


In [67]:
#set operations
set1 = {1,2,3,4,5,6}
set2 = {2,3,5,6,7,8,9}
print(set1 | set2) #union of two sets
print(set1.union(set2)) 
print(set1 & set2) #and operation
print(set1.intersection(set2))


{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{2, 3, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [71]:
#symmetric difference
print(set1 ^ set2) #individual each elements of set1 and set2
print(set1.symmetric_difference(set2))

#find subset
x = {"a","b","c","d","e","f"}
y = {"a","b"}
print("set 'x is subset of 'y' ? ",x.issubset(y))
print("set 'y is subset of 'x' ? ",y.issubset(x))

{1, 4, 7, 8, 9}
{1, 4, 7, 8, 9}
set 'x is subset of 'y' ?  False
set 'y is subset of 'x' ?  True


In [72]:
#frozen sets: its immutable like tuple(where set is mutalble),sets are not use as dictionary keys where frozen sets can be used as keys of dictinaries
se1 = frozenset([1,2,3,4])
set2 = frozenset([2,5,6,7])
set1.add(5) #there can't be add an element like set
print(set1.intersection(set2))

{2, 5, 6}


In [5]:
#tuple,list ordered,, dictionary unordered
#dictionary with mixed keys
my_dict = {'name':'satish', 1:['abc','xyz']}
print(my_dict)
my_dict1 = dict()
my_dict1= dict([(1,'abc'),(2,'xyz')])
print(my_dict1)

my_dict2 = {'name':'azhar','age':23,'address':'sylhet'}
print(my_dict2['name'])
#print(my_dict['degree']) #shows key error
my_dict2['name'] ='ibrahim' #update name
print(my_dict2)
my_dict2.popitem()
print(my_dict2) #remove an arbitrary key

{'name': 'satish', 1: ['abc', 'xyz']}
{1: 'abc', 2: 'xyz'}
azhar
{'name': 'ibrahim', 'age': 23, 'address': 'sylhet'}
{'name': 'ibrahim', 'age': 23}


In [8]:
squares = {2:4,3:9,4:16,5:25}
del squares[2]
print(squares)
subject = {}.fromkeys(['Math','English','Bangle'],0)
print(subject)
print(squares.keys())
print(squares.values())

{3: 9, 4: 16, 5: 25}
{'Math': 0, 'English': 0, 'Bangle': 0}
dict_keys([3, 4, 5])
dict_values([9, 16, 25])


In [9]:
#dict comprenshion
d = {'a':1, 'b':2,'c':3}
for pair in d.items():
    print(pair)

('a', 1)
('b', 2)
('c', 3)


In [10]:
new_dict = {k:v for k,v in d.items() if v>2}
print(new_dict)

{'c': 3}


In [12]:
#also perform operation on the key value pairs
d = {'a':1,'b':2,'c':3,'d':4,'e':5}
d = {k+'c':v*2 for k,v in d.items()  if v>2}
print(d)

{'cc': 6, 'dc': 8, 'ec': 10}


In [13]:
print('l' in 'Hello world')

True


In [14]:
"This will split all words in a list".split()

['This', 'will', 'split', 'all', 'words', 'in', 'a', 'list']

In [15]:
' '.join(['This','will','split','all','words','in','a','list'])

'This will split all words in a list'

In [16]:
"Bad Morning".replace("Bad","Good")

'Good Morning'

In [17]:
mystr = "MadaM"
mystr = mystr.lower()
revstr = reversed(mystr)
if list(mystr) == list(revstr):
    print("Given String is pallindrome")
else:
    print("Given string is not pallindrome")

Given String is pallindrome


In [19]:
mystr = "python program to sort words in alphabetic order"
words = mystr.split()
words.sort()
for word in words:
    print(word)

alphabetic
in
order
program
python
sort
to
words


In [20]:
#function
global_var = "This is global variable"
def test_life_time():
    local_var = "This is a local variable"
    print(local_var)
    print(global_var)
test_life_time()
print(global_var)
print(local_var)

This is a local variable
This is global variable
This is global variable


NameError: name 'local_var' is not defined

In [22]:
def computeHCF(a,b):
    smaller = b if a>b else a
    hcf =1 
    for i in range(1,smaller+1):
        if(a%i==0) and (b%i==0):
            hcf = i
    return hcf
num1=98
num2=78
print("H.C.F of {0} and {1} is:{2}".format(num1,num2,computeHCF(num1,num2)))

H.C.F of 98 and 78 is:2


In [27]:
lst = [1,2,3,4]
print(all(lst))
print(divmod(9,2))
number_list = range(-10,10)
print(list(number_list))
print(isinstance(lst,list))

True
(4, 1)
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
True


In [28]:
numbers = [1,2,3,4]
squared = []
for num in numbers:
    squared.append(num ** 2)
print(squared)

[1, 4, 9, 16]


In [29]:
def greet(name,msg="Good Morning"):
    print("Hello {0},{1}".format(name,msg))
greet("azhar","Good Night")

Hello azhar,Good Night


In [33]:
def greet(**kwargs):
    if kwargs:
        print("Hello {0},{1}".format(kwargs['name'],kwargs['msg']))
greet(name="azhar",msg="Good Night")

Hello azhar,Good Night


In [35]:
#recursion
def factorial(num):
    return 1 if num==1 else (num*factorial(num-1))
num = 5
print ("Factorial of {0} is {1}".format(num,factorial(num)))

Factorial of 5 is 120


In [36]:
def fibonacci(num):
    return num if num<=1 else fibonacci(num-1) + fibonacci(num-2)
nterms = 10
print("Fibonacci sequence")
for num in range(nterms):
    print(fibonacci(num))

Fibonacci sequence
0
1
1
2
3
5
8
13
21
34


In [38]:
#lambda function
double = lambda x:x*2
print(double(5))
lst = [1,2,3,4,5]
even_list = list(filter(lambda x: (x%2 == 0),lst))
print(even_list)

10
[2, 4]


In [39]:
from functools import reduce
lst = [1,2,3,4,5]
product_lst = reduce(lambda x,y:x*y,lst)
print(product_lst)

120


In [41]:
import datetime 
datetime.datetime.now()
import math as m
print(m.pi)

3.141592653589793


In [42]:
from math import * #it means import all the module of math
print("Value of PI is " +str(pi))

Value of PI is 3.141592653589793


In [43]:
#import module sys to get the type of exception
import sys
lst = ['b',0,2]
for entry in lst:
    try:
        print("The entry is",entry)
        r = 1/int(entry)
    except:
        print("Oops!",sys.exc_info()[0],"occured")
        print("Next Entry")
        print("***************")
print("The reciprocal of",entry,"is",r)

The entry is b
Oops! <class 'ValueError'> occured
Next Entry
***************
The entry is 0
Oops! <class 'ZeroDivisionError'> occured
Next Entry
***************
The entry is 2
The reciprocal of 2 is 0.5


In [44]:
lst = ['b',0,2]
for entry in lst:
    try:
        print("************")
        print("The entry is",entry)
        r = 1/int(entry)
    except(ValueError):
        print("This is ValueError")
    except(ZeroDivisionError):
        print("This is ZeroError")
    except:
        print("Some other error")
print("The reciprocal of",entry,"is",r)

************
The entry is b
This is ValueError
************
The entry is 0
This is ZeroError
************
The entry is 2
The reciprocal of 2 is 0.5


In [46]:
try:
    num = int(input("Enter a positive integer:"))
    if num <= 0:
        raise ValueError("Error:Entered negative number")
except ValueError as e:
    print(e)

Enter a positive integer:-10
Error:Entered negative number


In [48]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [49]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

561 µs ± 111 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [50]:
a = np.arange(1000)
%timeit a**2

2.85 µs ± 514 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
#2-D, 3-D
b = np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [52]:
b.ndim

2

In [53]:
c = np.array([[[0,1],[2,3]],[ [4,5],[6,7] ]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
c.shape

(2, 2, 2)

In [59]:
#using linespace
a = np.linspace(0, 1, 6) #start,end,number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [60]:
#common arrays
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.eye(3,2) #no fo row is 3 and no of col is 2

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [63]:
#create array using diag function
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [64]:
a = np.random.rand(4)
a

array([0.22176344, 0.22762322, 0.07021505, 0.61958774])

In [65]:
a = np.random.randn(4)
a

array([-0.29339271, -0.92574833,  0.25786692,  0.91397009])

In [66]:
a = np.arange(10)
a.dtype

dtype('int32')

In [67]:
a =np.arange(10,dtype='float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [71]:
d = np.array([1+2j, 2+4j])
print(d.dtype)

complex128


In [72]:
b = np.array([True,False,True,False])
print(b.dtype)

bool


In [73]:
s = np.array(['Ram','Robert','Azhar'])
s.dtype

dtype('<U6')

In [75]:
#for multidimensional arrays,indexes are tuples of integers
a = np.diag([1,2,3])
print(a[2][2])

3


In [76]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [77]:
a = np.arange(10)
a[5:] = 10
a


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [78]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [80]:
a = np.arange(10)
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [81]:
np.shares_memory(a,b)

True

In [82]:
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [83]:
np.shares_memory(a,c)

False

In [84]:
a = np.random.randint(0,20,15)
a

array([ 2,  6, 17,  3, 17, 17, 15,  8, 16,  2,  6,  7, 15, 19, 13])

In [85]:
mask = (a%2==0)
extract_from_a = a[mask]
extract_from_a

array([ 2,  6,  8, 16,  2,  6])

In [86]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [90]:
a[[9,7]] =-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [91]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [92]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [93]:
b=np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [94]:
c =np.diag([1,2,3,4])
print(c*c)
print("*********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [95]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [96]:
x = np.array([1,2,3,4])
x.sum(axis=0) #add in columns

10

In [98]:
x.argmin() #index of minimum element

0

In [100]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True

In [105]:
y = np.array([[1,2,3],[5,6,1]])
np.median(y,axis=-1) #row wise

array([2., 5.])